build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [php-scrutinizer-run]
    # coverage:
    #   tests:
    #     override:
    #       - command: composer run test
    #         coverage:
    #           file: ./build/phpunit/clover.xml
    #           format: clover

filter:
  excluded_paths: [build/*, docs/*, tests/*, vendor/*]

before_commands:
  - "composer install --dev --prefer-source"

checks:
  php:
    remove_extra_empty_lines: false
    remove_php_closing_tag: true
    remove_trailing_whitespace: true
    fix_use_statements:
      remove_unused: true
      preserve_multiple: false
      preserve_blanklines: true
      order_alphabetically: false
    fix_php_opening_tag: true
    fix_linefeed: true
    fix_line_ending: true
    fix_identation_4spaces: true
    fix_doc_comments: true

tools:
  external_code_coverage:
    timeout: 600
    runs: 3
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_code_coverage: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs: [vendor, tests, build, docs]
